version: '3.7'

services:
  mongo1-rtdb:
    container_name: mongo1-rtdb
    image: mongo:4.4.6-bionic
    command: mongod --replSet my-mongo-set
    ports:
      - 27014:27017
    networks:
      - practicas
    volumes:
      #- ./.dev/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./.dev/dbs:/dbs
      #- ./.dev/data/mongo-db/data:/data/db

  mongo2-rtdb:
    container_name: mongo2-rtdb
    image: mongo:4.4.6-bionic
    command: mongod --replSet my-mongo-set
    ports:
      - 27015:27017
    networks:
      - practicas
    volumes:
      #- ./.dev/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./.dev/dbs:/dbs
      #- ./.dev/data/mongo-db/data:/data/db
  
  mongo3-rtdb:
    container_name: mongo3-rtdb
    image: mongo:4.4.6-bionic
    command: mongod --replSet my-mongo-set
    ports:
      - 27016:27017
    networks:
      - practicas
    volumes:
      #- ./.dev/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./.dev/dbs:/dbs
      #- ./.dev/data/mongo-db/data:/data/db

  nodejs:
    build: .
    container_name: nodejs
    depends_on:
      - mongo1-rtdb
      - mongo2-rtdb
      - mongo3-rtdb
    environment:
      - SERVER_PORT=8090
    ports:
      - 8090:8090
    networks:
      - practicas
    volumes:
      - ./:/srv/app

networks:
  practicas: