version: '3.7'

services:
  mongo:
    image: mongo:4.4.6-bionic
    container_name: mongodb
    #command: --bind_ip 0.0.0.0
    ports:
      - 27017:27017
    networks:
      - practicas
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: capital28_dev
    volumes:
      # mongo initialize startup activities and restore task
      - ./.dev/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
      # volume with db files
      - ./.dev/dbs:/dbs/
      # volume with mongo db data
      - ./.dev/data/mongo-db/data:/data/db/

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    networks:
      - practicas
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin

  real-time-db:
    image: node:14-alpine3.13
    build:
      context: .
    depends_on:
      - mongo
    environment:
      - SERVER_PORT=8090
      - CONNECTIONSTRING=mongodb://mongodb:27017/c28_db
    ports:
      - 8090:8090
    networks:
      - practicas
    volumes:
      - ./:/srv/app
    command: npm run debug

networks:
  practicas:
    name: practicas